FROM php:8.4-fpm

WORKDIR /app

RUN apt-get update && apt-get install -y \
    unzip git curl \
    && rm -rf /var/lib/apt/lists/*

COPY --from=composer:2 /usr/bin/composer /usr/bin/composer

COPY app/composer.json app/composer.lock ./

RUN composer install --no-interaction --prefer-dist --no-dev

# THEN copy source code
COPY app/ ./

CMD ["php", "runner/main.php"]