FROM php:8.4-fpm

WORKDIR /app

RUN apt-get update && apt-get install -y \
    unzip git curl \
    && rm -rf /var/lib/apt/lists/*

RUN docker-php-ext-install pdo pdo_mysql

COPY --from=composer:2 /usr/bin/composer /usr/bin/composer

COPY app/composer.json app/composer.lock ./

RUN composer install --no-interaction --prefer-dist --no-dev

COPY app/ ./

CMD ["php", "worker/main.php"]