CREATE TABLE failed_jobs (
    id INT AUTO_INCREMENT PRIMARY KEY,
    external_id VARCHAR(20) NOT NULL,
    file VARCHAR(255) NOT NULL,
    exception VARCHAR(255) NOT NULL,

    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);